# Étape 1 : Utiliser une image de base
FROM node:18

# Étape 2 : Définir le répertoire de travail
WORKDIR /app/StreamFront

RUN apt-get update && apt-get install -y git jq

# Étape 4 : Cloner le dépôt GitHub dans le répertoire StreamFront
COPY ./streamfront/ .

COPY ./video.mp4 ./src/assets/video.mp4

# Étape 4 : Ajouter le script start au package.json
RUN jq '.scripts.start = "vite"' package.json > tmp.json && mv tmp.json package.json

# Étape 5 : Installer les dépendances
RUN npm install

# Étape 6 : Copier le reste des fichiers du projet
COPY . .

# Étape 8 : Exposer le port 3000
EXPOSE 5173

# Étape 9 : Démarrer l'application
CMD ["npm", "run", "dev", "--host"]
