FROM golang:1.23.1 AS BUILD

WORKDIR /var/www/masterNode

COPY masterNode .

RUN go mod tidy

# RUN go test ./...

RUN go build . masterNode

# ============================

FROM debian:latest as PROD

WORKDIR /var/www/masterNode

COPY --from=BUILD --chown=www-data:www-data /var/www/masterNode/masterNode .

EXPOSE 8080

CMD ["/var/www/masterNode/masterNode"]
